gcs_raw_data_bucket_name: "mlops_101_raw_taxi_data"
gcs_processed_taxi_data_bucket_name: "mlops_101_processed_taxi_data"

taxi_data_years: [2024]
taxi_data_months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
taxi_type: "green"

green_taxi_raw_schema:
  - name: "VendorID"
    type: "int"
  - name: "lpep_pickup_datetime"
    type: "datetime"
  - name: "lpep_dropoff_datetime"
    type: "datetime"
  - name: "store_and_fwd_flag"
    type: "string"
  - name: "RatecodeID"
    type: "float"
  - name: "PULocationID"
    type: "int"
  - name: "DOLocationID"
    type: "int"
  - name: "passenger_count"
    type: "float"
  - name: "trip_distance"
    type: "float"
  - name: "fare_amount"
    type: "float"
  - name: "extra"
    type: "float"
  - name: "mta_tax"
    type: "float"
  - name: "tip_amount"
    type: "float"
  - name: "tolls_amount"
    type: "float"
  - name: "ehail_fee"
    type: "float"
  - name: "improvement_surcharge"
    type: "float"
  - name: "total_amount"
    type: "float"
  - name: "payment_type"
    type: "float"
  - name: "trip_type"
    type: "float"
  - name: "congestion_surcharge"
    type: "float"

num_features:
  - passenger_count
  - trip_type
  - congestion_surcharge
  - mean_distance
  - mean_duration
  - rush_hour

cat_features:
  - vendor_id

target:
  - fare_amount

train_file_name: "green_taxi_train_set.parquet"
test_file_name: "green_taxi_test_set.parquet"

experiment_name: "taxi_fare_prediction"
