name: Build & Deploy Model API to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mlops-101
  REGION: asia-northeast3
  GAR_LOCATION: asia-northeast3-docker.pkg.dev/mlops-101/fastapi-taxi-fare-predictor
  IMAGE_NAME: fastapi-taxi-fare-predictor
  IMAGE_TAG: latest

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python
        run: uv python install 3.11

      - name: Install the dependencies
        run: |
          uv sync --all-extras

      - name: Run pre-commit checks
        run: |
          uv run pre-commit run --all-files

      - name: Run pytest
        run: |
          uv run pytest

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: "Checkout"
      uses: "actions/checkout@v3"

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Set up Cloud SDK
      uses: "google-github-actions/setup-gcloud@v1"
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        install_components: "gke-gcloud-auth-plugin"
        export_default_credentials: true

    - name: Use gcloud CLI
      run: "gcloud info"

    - name: Docker auth
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build image
      run: docker build --build-arg MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }} . --file Dockerfile --tag ${{ env.GAR_LOCATION }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      working-directory: src/make_api

    - name: Push image
      run: docker push ${{ env.GAR_LOCATION }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials mlops-101-my-autopilot-cluster --region asia-northeast3 --project mlops-101
        kubectl apply -f src/make_api/resources.yaml
