name: Deploy API to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: fake-app-323017
  REGION: asia-northeast3
  GAR_LOCATION: asia-northeast3-docker.pkg.dev/mlops-101/fastapi-taxi-fare-predictor

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: "actions/checkout@v3"

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build image
      run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}
      working-directory: src/make_api

    - name: Push image
      run: docker push ${{ env.GAR_LOCATION }}
